### ISSUE TITLE
Configure Travis CI Pipeline

### ISSUE THREAD

**Issue by AmanAb428** [byte-pushers/bp-web#104]
@pouncilt 

To configure the Travis CI for the private GitHub repository, we need below inputs.
- Admin Access
- Paid Subscription (100 Free builds, Later on it would be chargeable)

<img width="956" alt="Screen Shot 2020-10-27 at 11 19 29 AM" src="https://user-images.githubusercontent.com/69825447/97344721-5bb07380-1846-11eb-9651-f2a96d2889ba.png">

We can take few more benefits from the paid version. Like,
- Deploy the Cloudformation template directly from Travis CI build job. (Currently, we are deploying from our Java code, which can be migrated to Travis-CI also)

**Reference Link:** https://docs.travis-ci.com/user/deployment-v2/providers/cloudformation/

**Comment by pouncilt** [comment]
@AmanAb428 Do you have an update on this issue?  Is this issue resolved?

**Comment by AmanAb428** [comment]
@pouncilt Yes. we achieved the actual purpose of this ticket including the deployment using travis cloudformation plugin.

**Comment by pouncilt** [comment]
Okay Lets close this issue.  I think we are on the Bootstrap plan.  How would the startup plan benefit us?

Thanks,

Tonté
