### ISSUE TITLE
As a user I want to see real content on BP Service page so that I know what services BP offers.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/bp-web#127]
**Tasks**
- text content needs to be read through and bolded for emphasis.
- Quote needs to be aligned properly in mobile view.
-images need to be resized and adjusted.

**Comment by pouncilt** [comment]
@ocampd1 Can you verify that this is done and report back?  Thanks.

**Comment by ocampd1** [comment]
Work was complete, no longer a valid issue.
