### ISSUE TITLE
Automate the AWS cloud formation deployment via travis

### ISSUE THREAD

**Issue by AmanAb428** [byte-pushers/bp-web#151]
Automate the CI/CD via travis instead of using java deployment (Currently using this -> mvn clean deploy)

**Comment by pouncilt** [comment]
@AmanAb428 Do you have an update on this issue?

**Comment by AmanAb428** [comment]
@pouncilt Yes. this is done already and we are using travis for the deployment instead of Java deployment

**Comment by pouncilt** [comment]
Okay Lets close this issue.

Thanks,

Tonté
