### ISSUE TITLE
SPIKE: Server less Lambda: After some it is getting sleep

### ISSUE THREAD

**Issue by AmanAb428** [byte-pushers/bp-web#152]

**Comment by pouncilt** [comment]
@AmanAb428 Do you have an update on this issue?

**Comment by AmanAb428** [comment]
@pouncilt 

We have 2 approaches here.
1. Retry logic on the client side application.
2. Increase the memory for lambda function. We are expecting to have at least 1500MB. This required to to review the pricing on AWS. Attaching the reference link here to review. https://aws.amazon.com/lambda/pricing/
3. We can schedule a health check endpoint trigger periodically to restrict the Lambda to sleep.

**Comment by pouncilt** [comment]
Oh okay.  I remember the issue now.  I think we are leaning with option 1.  BTW, I’ve implemented this one already for both BP and CP3.  Lets also look talk more about option 2 today.

Thanks,

Tonté

**Comment by pouncilt** [comment]
Yeah we can definitely increase the memory.  Currently the retry logic seems to be working okay.  Will close this issue right now.
