### ISSUE TITLE
As a user I want to quickly navigate through the contact page.

### ISSUE THREAD

**Issue by ocampd1** [byte-pushers/bp-web#168]
User should be able to quickly fill out the contact form but if they wish to detail more they can do so with a click of a button.

- Add a "See More" button to the Personal Information aspect of the form.  Will hide any inputs after the phone input.
- Add a "See More" button to the Business Information aspect of the form. Will hide drop down inputs and budget inputs.
- Adjust  'required' on the following:

> - city
> - state
> - business
> - year
> - type
> - platform
> - budget
> - timeline

**Comment by ocampd1** [comment]
Ready to close pending PR.

**Comment by ocampd1** [comment]
PR is now merged.

**Comment by pouncilt** [comment]
Implemented.
