### ISSUE TITLE
BACKLOG: As a developer I want to keep my CSS files under memory budget

### ISSUE THREAD

**Issue by ocampd1** [byte-pushers/bp-web#179]
**For Angular featuring regarding budgets:** https://stackoverflow.com/questions/53995948/warning-in-budgets-maximum-exceeded-for-initial

https://blog.logrocket.com/the-complete-best-practices-for-minifying-css/

- WARNING in C:/Users/ninte/dev/bp-web/bp-web-client/angular-app/src/app/components/app-contact/app--contact.component.css exceeded maximum budget. Budget 9 kB was not met by 1.61 kB with a total of 10.6 kB.

- WARNING in C:/Users/ninte/dev/bp-web/bp-web-client/angular-app/src/app/components/app-home/app-home.component.css exceeded maximum budget. Budget 9 kB was not met by 7.76 kB with a total of 16.8 kB.

- WARNING in C:/Users/ninte/dev/bp-web/bp-web-client/angular-app/src/app/components/app-services/app-services.component.css exceeded maximum budget. Budget 9 kB was not met by 2.71 kB with a total of 11.7 kB.

- WARNING in C:/Users/ninte/dev/bp-web/bp-web-client/angular-app/src/app/shared/components/app-header.component/app-header.component.css exceeded maximum budget. Budget 9 kB was not met by 58.7 kB with a total of 67.7 kB.

------------------------

-Move new styles to styles and work strategically to create css groupings.

**Comment by pouncilt** [comment]
Do a quick search and see what the recommended solution is for error message.  Also see what the best practices are for this.

**Comment by ocampd1** [comment]
complete.
