### ISSUE TITLE
BUG: As a user id like to avoid encountering a bug when filling out my phone number

### ISSUE THREAD

**Issue by ocampd1** [byte-pushers/bp-web#193]
There's a range error that gets called after formatting the phone number.
It reads "Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded"

**Comment by pouncilt** [comment]
This bug seem to have disappeared.

**Comment by pouncilt** [comment]
Spoke too soon!

**Comment by pouncilt** [comment]
Fixed.

**Comment by pouncilt** [comment]
Use this RegEx for phone number format:  https://stackoverflow.com/questions/16699007/regular-expression-to-match-standard-10-digit-phone-number
